//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePetResort.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetOwner
    {
        public int PetOwnerID { get; set; }
        public string OwnerID { get; set; }
        public int PetID { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
