//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePetResort.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetResortEntities : DbContext
    {
        public PetResortEntities()
            : base("name=PetResortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<PetOwner> PetOwners { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<ReservationLimit> ReservationLimits { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ResortLocation> ResortLocations { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
