//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using JQueryUIHelpers;

namespace ThePetResort.DAL
{
    using System;
    using System.Collections.Generic;


    public partial class Reservation
    {
        [Display(Name = "Reservation")]
        public int ReservationID { get; set; }

        [Display(Name = "Location")]
        public int ResortLocationID { get; set; }
        public int PetID { get; set; }
        public System.DateTime ReservationDate { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual ResortLocation ResortLocation { get; set; }
    }
}
