//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePetResort.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationLimit
    {
        public int ReservationLimitID { get; set; }
        public int ResortLocationID { get; set; }
        public int TypeID { get; set; }
        public byte Limit { get; set; }
    
        public virtual ResortLocation ResortLocation { get; set; }
        public virtual Type Type { get; set; }
    }
}
